//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.NegociacionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pago", Namespace="http://www.banmedica.cl/Recuadacion/Bancobro/Negociacion")]
    [System.SerializableAttribute()]
    public partial class Pago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long FolioField;
        
        private string FechaGeneracionField;
        
        private WS_Ingresos.NegociacionService.EstadoPlanilla EstadoField;
        
        private long MontoTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WS_Ingresos.NegociacionService.DetallePago[] PeriodosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Folio {
            get {
                return this.FolioField;
            }
            set {
                if ((this.FolioField.Equals(value) != true)) {
                    this.FolioField = value;
                    this.RaisePropertyChanged("Folio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string FechaGeneracion {
            get {
                return this.FechaGeneracionField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaGeneracionField, value) != true)) {
                    this.FechaGeneracionField = value;
                    this.RaisePropertyChanged("FechaGeneracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public WS_Ingresos.NegociacionService.EstadoPlanilla Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long MontoTotal {
            get {
                return this.MontoTotalField;
            }
            set {
                if ((this.MontoTotalField.Equals(value) != true)) {
                    this.MontoTotalField = value;
                    this.RaisePropertyChanged("MontoTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public WS_Ingresos.NegociacionService.DetallePago[] Periodos {
            get {
                return this.PeriodosField;
            }
            set {
                if ((object.ReferenceEquals(this.PeriodosField, value) != true)) {
                    this.PeriodosField = value;
                    this.RaisePropertyChanged("Periodos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoPlanilla", Namespace="http://www.banmedica.cl/Recuadacion/Bancobro/Negociacion")]
    public enum EstadoPlanilla : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Generada = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pagada = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Anulada = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetallePago", Namespace="http://www.banmedica.cl/Recuadacion/Bancobro/Negociacion")]
    [System.SerializableAttribute()]
    public partial class DetallePago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PeriodoField;
        
        private int MontoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Periodo {
            get {
                return this.PeriodoField;
            }
            set {
                if ((this.PeriodoField.Equals(value) != true)) {
                    this.PeriodoField = value;
                    this.RaisePropertyChanged("Periodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.banmedica.cl/Recuadacion/Bancobro/Negociacion", ConfigurationName="NegociacionService.NegociacionSoap")]
    public interface NegociacionSoap {
        
        // CODEGEN: Generating message contract since element name isapre from namespace http://www.banmedica.cl/Recuadacion/Bancobro/Negociacion is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banmedica.cl/Recuadacion/Bancobro/Negociacion/ObtenerPagosPorRutIsapre" +
            "", ReplyAction="*")]
        WS_Ingresos.NegociacionService.ObtenerPagosPorRutIsapreResponse ObtenerPagosPorRutIsapre(WS_Ingresos.NegociacionService.ObtenerPagosPorRutIsapreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banmedica.cl/Recuadacion/Bancobro/Negociacion/ObtenerPagosPorRutIsapre" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_Ingresos.NegociacionService.ObtenerPagosPorRutIsapreResponse> ObtenerPagosPorRutIsapreAsync(WS_Ingresos.NegociacionService.ObtenerPagosPorRutIsapreRequest request);
        
        // CODEGEN: Generating message contract since element name ObtenerPagoPorFolioResult from namespace http://www.banmedica.cl/Recuadacion/Bancobro/Negociacion is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banmedica.cl/Recuadacion/Bancobro/Negociacion/ObtenerPagoPorFolio", ReplyAction="*")]
        WS_Ingresos.NegociacionService.ObtenerPagoPorFolioResponse ObtenerPagoPorFolio(WS_Ingresos.NegociacionService.ObtenerPagoPorFolioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banmedica.cl/Recuadacion/Bancobro/Negociacion/ObtenerPagoPorFolio", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_Ingresos.NegociacionService.ObtenerPagoPorFolioResponse> ObtenerPagoPorFolioAsync(WS_Ingresos.NegociacionService.ObtenerPagoPorFolioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPagosPorRutIsapreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPagosPorRutIsapre", Namespace="http://www.banmedica.cl/Recuadacion/Bancobro/Negociacion", Order=0)]
        public WS_Ingresos.NegociacionService.ObtenerPagosPorRutIsapreRequestBody Body;
        
        public ObtenerPagosPorRutIsapreRequest() {
        }
        
        public ObtenerPagosPorRutIsapreRequest(WS_Ingresos.NegociacionService.ObtenerPagosPorRutIsapreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banmedica.cl/Recuadacion/Bancobro/Negociacion")]
    public partial class ObtenerPagosPorRutIsapreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int rut;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string isapre;
        
        public ObtenerPagosPorRutIsapreRequestBody() {
        }
        
        public ObtenerPagosPorRutIsapreRequestBody(int rut, string isapre) {
            this.rut = rut;
            this.isapre = isapre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPagosPorRutIsapreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPagosPorRutIsapreResponse", Namespace="http://www.banmedica.cl/Recuadacion/Bancobro/Negociacion", Order=0)]
        public WS_Ingresos.NegociacionService.ObtenerPagosPorRutIsapreResponseBody Body;
        
        public ObtenerPagosPorRutIsapreResponse() {
        }
        
        public ObtenerPagosPorRutIsapreResponse(WS_Ingresos.NegociacionService.ObtenerPagosPorRutIsapreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banmedica.cl/Recuadacion/Bancobro/Negociacion")]
    public partial class ObtenerPagosPorRutIsapreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_Ingresos.NegociacionService.Pago[] ObtenerPagosPorRutIsapreResult;
        
        public ObtenerPagosPorRutIsapreResponseBody() {
        }
        
        public ObtenerPagosPorRutIsapreResponseBody(WS_Ingresos.NegociacionService.Pago[] ObtenerPagosPorRutIsapreResult) {
            this.ObtenerPagosPorRutIsapreResult = ObtenerPagosPorRutIsapreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPagoPorFolioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPagoPorFolio", Namespace="http://www.banmedica.cl/Recuadacion/Bancobro/Negociacion", Order=0)]
        public WS_Ingresos.NegociacionService.ObtenerPagoPorFolioRequestBody Body;
        
        public ObtenerPagoPorFolioRequest() {
        }
        
        public ObtenerPagoPorFolioRequest(WS_Ingresos.NegociacionService.ObtenerPagoPorFolioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banmedica.cl/Recuadacion/Bancobro/Negociacion")]
    public partial class ObtenerPagoPorFolioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long folio;
        
        public ObtenerPagoPorFolioRequestBody() {
        }
        
        public ObtenerPagoPorFolioRequestBody(long folio) {
            this.folio = folio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPagoPorFolioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPagoPorFolioResponse", Namespace="http://www.banmedica.cl/Recuadacion/Bancobro/Negociacion", Order=0)]
        public WS_Ingresos.NegociacionService.ObtenerPagoPorFolioResponseBody Body;
        
        public ObtenerPagoPorFolioResponse() {
        }
        
        public ObtenerPagoPorFolioResponse(WS_Ingresos.NegociacionService.ObtenerPagoPorFolioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banmedica.cl/Recuadacion/Bancobro/Negociacion")]
    public partial class ObtenerPagoPorFolioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_Ingresos.NegociacionService.Pago ObtenerPagoPorFolioResult;
        
        public ObtenerPagoPorFolioResponseBody() {
        }
        
        public ObtenerPagoPorFolioResponseBody(WS_Ingresos.NegociacionService.Pago ObtenerPagoPorFolioResult) {
            this.ObtenerPagoPorFolioResult = ObtenerPagoPorFolioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NegociacionSoapChannel : WS_Ingresos.NegociacionService.NegociacionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NegociacionSoapClient : System.ServiceModel.ClientBase<WS_Ingresos.NegociacionService.NegociacionSoap>, WS_Ingresos.NegociacionService.NegociacionSoap {
        
        public NegociacionSoapClient() {
        }
        
        public NegociacionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NegociacionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NegociacionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NegociacionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_Ingresos.NegociacionService.ObtenerPagosPorRutIsapreResponse WS_Ingresos.NegociacionService.NegociacionSoap.ObtenerPagosPorRutIsapre(WS_Ingresos.NegociacionService.ObtenerPagosPorRutIsapreRequest request) {
            return base.Channel.ObtenerPagosPorRutIsapre(request);
        }
        
        public WS_Ingresos.NegociacionService.Pago[] ObtenerPagosPorRutIsapre(int rut, string isapre) {
            WS_Ingresos.NegociacionService.ObtenerPagosPorRutIsapreRequest inValue = new WS_Ingresos.NegociacionService.ObtenerPagosPorRutIsapreRequest();
            inValue.Body = new WS_Ingresos.NegociacionService.ObtenerPagosPorRutIsapreRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.isapre = isapre;
            WS_Ingresos.NegociacionService.ObtenerPagosPorRutIsapreResponse retVal = ((WS_Ingresos.NegociacionService.NegociacionSoap)(this)).ObtenerPagosPorRutIsapre(inValue);
            return retVal.Body.ObtenerPagosPorRutIsapreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_Ingresos.NegociacionService.ObtenerPagosPorRutIsapreResponse> WS_Ingresos.NegociacionService.NegociacionSoap.ObtenerPagosPorRutIsapreAsync(WS_Ingresos.NegociacionService.ObtenerPagosPorRutIsapreRequest request) {
            return base.Channel.ObtenerPagosPorRutIsapreAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_Ingresos.NegociacionService.ObtenerPagosPorRutIsapreResponse> ObtenerPagosPorRutIsapreAsync(int rut, string isapre) {
            WS_Ingresos.NegociacionService.ObtenerPagosPorRutIsapreRequest inValue = new WS_Ingresos.NegociacionService.ObtenerPagosPorRutIsapreRequest();
            inValue.Body = new WS_Ingresos.NegociacionService.ObtenerPagosPorRutIsapreRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.isapre = isapre;
            return ((WS_Ingresos.NegociacionService.NegociacionSoap)(this)).ObtenerPagosPorRutIsapreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_Ingresos.NegociacionService.ObtenerPagoPorFolioResponse WS_Ingresos.NegociacionService.NegociacionSoap.ObtenerPagoPorFolio(WS_Ingresos.NegociacionService.ObtenerPagoPorFolioRequest request) {
            return base.Channel.ObtenerPagoPorFolio(request);
        }
        
        public WS_Ingresos.NegociacionService.Pago ObtenerPagoPorFolio(long folio) {
            WS_Ingresos.NegociacionService.ObtenerPagoPorFolioRequest inValue = new WS_Ingresos.NegociacionService.ObtenerPagoPorFolioRequest();
            inValue.Body = new WS_Ingresos.NegociacionService.ObtenerPagoPorFolioRequestBody();
            inValue.Body.folio = folio;
            WS_Ingresos.NegociacionService.ObtenerPagoPorFolioResponse retVal = ((WS_Ingresos.NegociacionService.NegociacionSoap)(this)).ObtenerPagoPorFolio(inValue);
            return retVal.Body.ObtenerPagoPorFolioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_Ingresos.NegociacionService.ObtenerPagoPorFolioResponse> WS_Ingresos.NegociacionService.NegociacionSoap.ObtenerPagoPorFolioAsync(WS_Ingresos.NegociacionService.ObtenerPagoPorFolioRequest request) {
            return base.Channel.ObtenerPagoPorFolioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_Ingresos.NegociacionService.ObtenerPagoPorFolioResponse> ObtenerPagoPorFolioAsync(long folio) {
            WS_Ingresos.NegociacionService.ObtenerPagoPorFolioRequest inValue = new WS_Ingresos.NegociacionService.ObtenerPagoPorFolioRequest();
            inValue.Body = new WS_Ingresos.NegociacionService.ObtenerPagoPorFolioRequestBody();
            inValue.Body.folio = folio;
            return ((WS_Ingresos.NegociacionService.NegociacionSoap)(this)).ObtenerPagoPorFolioAsync(inValue);
        }
    }
}
