//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    
    public partial class AfiliadoCertificadoEntity
    {
        public string NOMBRE { get; set; }
        public decimal AFIL_NRUT { get; set; }
        public Nullable<System.DateTime> AFIL_FINICIO_VIGENCIA_BENEFIC { get; set; }
    }
}
