//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BancobroProdEntities : DbContext
    {
        public BancobroProdEntities()
            : base("name=BancobroProdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int PKG_RECAUDACIONES_SP_GENERA_PLANILLA(Nullable<decimal> iN_FOLIOPAGO, Nullable<decimal> iN_TIPO, Nullable<decimal> iN_AFIL_NRUT, string iN_ISAPRE, Nullable<decimal> iN_MGASTOCOBTOTAL, Nullable<decimal> iN_MGASTOCOB, Nullable<decimal> iN_MPAGO, Nullable<decimal> iN_PREMUN, Nullable<decimal> iN_CSUBPRODUCTO, Nullable<decimal> iN_MDEUDA, Nullable<decimal> iN_MREAJUSTE, Nullable<decimal> iN_MINTERES, Nullable<decimal> iN_MRECARGO, Nullable<decimal> iN_MHONORARIO, ObjectParameter oUT_RETORNO)
        {
            var iN_FOLIOPAGOParameter = iN_FOLIOPAGO.HasValue ?
                new ObjectParameter("IN_FOLIOPAGO", iN_FOLIOPAGO) :
                new ObjectParameter("IN_FOLIOPAGO", typeof(decimal));
    
            var iN_TIPOParameter = iN_TIPO.HasValue ?
                new ObjectParameter("IN_TIPO", iN_TIPO) :
                new ObjectParameter("IN_TIPO", typeof(decimal));
    
            var iN_AFIL_NRUTParameter = iN_AFIL_NRUT.HasValue ?
                new ObjectParameter("IN_AFIL_NRUT", iN_AFIL_NRUT) :
                new ObjectParameter("IN_AFIL_NRUT", typeof(decimal));
    
            var iN_ISAPREParameter = iN_ISAPRE != null ?
                new ObjectParameter("IN_ISAPRE", iN_ISAPRE) :
                new ObjectParameter("IN_ISAPRE", typeof(string));
    
            var iN_MGASTOCOBTOTALParameter = iN_MGASTOCOBTOTAL.HasValue ?
                new ObjectParameter("IN_MGASTOCOBTOTAL", iN_MGASTOCOBTOTAL) :
                new ObjectParameter("IN_MGASTOCOBTOTAL", typeof(decimal));
    
            var iN_MGASTOCOBParameter = iN_MGASTOCOB.HasValue ?
                new ObjectParameter("IN_MGASTOCOB", iN_MGASTOCOB) :
                new ObjectParameter("IN_MGASTOCOB", typeof(decimal));
    
            var iN_MPAGOParameter = iN_MPAGO.HasValue ?
                new ObjectParameter("IN_MPAGO", iN_MPAGO) :
                new ObjectParameter("IN_MPAGO", typeof(decimal));
    
            var iN_PREMUNParameter = iN_PREMUN.HasValue ?
                new ObjectParameter("IN_PREMUN", iN_PREMUN) :
                new ObjectParameter("IN_PREMUN", typeof(decimal));
    
            var iN_CSUBPRODUCTOParameter = iN_CSUBPRODUCTO.HasValue ?
                new ObjectParameter("IN_CSUBPRODUCTO", iN_CSUBPRODUCTO) :
                new ObjectParameter("IN_CSUBPRODUCTO", typeof(decimal));
    
            var iN_MDEUDAParameter = iN_MDEUDA.HasValue ?
                new ObjectParameter("IN_MDEUDA", iN_MDEUDA) :
                new ObjectParameter("IN_MDEUDA", typeof(decimal));
    
            var iN_MREAJUSTEParameter = iN_MREAJUSTE.HasValue ?
                new ObjectParameter("IN_MREAJUSTE", iN_MREAJUSTE) :
                new ObjectParameter("IN_MREAJUSTE", typeof(decimal));
    
            var iN_MINTERESParameter = iN_MINTERES.HasValue ?
                new ObjectParameter("IN_MINTERES", iN_MINTERES) :
                new ObjectParameter("IN_MINTERES", typeof(decimal));
    
            var iN_MRECARGOParameter = iN_MRECARGO.HasValue ?
                new ObjectParameter("IN_MRECARGO", iN_MRECARGO) :
                new ObjectParameter("IN_MRECARGO", typeof(decimal));
    
            var iN_MHONORARIOParameter = iN_MHONORARIO.HasValue ?
                new ObjectParameter("IN_MHONORARIO", iN_MHONORARIO) :
                new ObjectParameter("IN_MHONORARIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PKG_RECAUDACIONES_SP_GENERA_PLANILLA", iN_FOLIOPAGOParameter, iN_TIPOParameter, iN_AFIL_NRUTParameter, iN_ISAPREParameter, iN_MGASTOCOBTOTALParameter, iN_MGASTOCOBParameter, iN_MPAGOParameter, iN_PREMUNParameter, iN_CSUBPRODUCTOParameter, iN_MDEUDAParameter, iN_MREAJUSTEParameter, iN_MINTERESParameter, iN_MRECARGOParameter, iN_MHONORARIOParameter, oUT_RETORNO);
        }
    
        public virtual int PKG_RECAUDACIONES_SP_ACT_ESTADO_PLANILLA(Nullable<decimal> iN_FOLIOPAGO, Nullable<decimal> iN_AGENCIA, string iN_ISAPRE, ObjectParameter oUT_RETORNO)
        {
            var iN_FOLIOPAGOParameter = iN_FOLIOPAGO.HasValue ?
                new ObjectParameter("IN_FOLIOPAGO", iN_FOLIOPAGO) :
                new ObjectParameter("IN_FOLIOPAGO", typeof(decimal));
    
            var iN_AGENCIAParameter = iN_AGENCIA.HasValue ?
                new ObjectParameter("IN_AGENCIA", iN_AGENCIA) :
                new ObjectParameter("IN_AGENCIA", typeof(decimal));
    
            var iN_ISAPREParameter = iN_ISAPRE != null ?
                new ObjectParameter("IN_ISAPRE", iN_ISAPRE) :
                new ObjectParameter("IN_ISAPRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PKG_RECAUDACIONES_SP_ACT_ESTADO_PLANILLA", iN_FOLIOPAGOParameter, iN_AGENCIAParameter, iN_ISAPREParameter, oUT_RETORNO);
        }
    
        public virtual int PKG_RECAUDACIONES_SECUENCIA_PAGOCOTIZA(ObjectParameter oUT_FOLIO, ObjectParameter oUT_RETORNO)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PKG_RECAUDACIONES_SECUENCIA_PAGOCOTIZA", oUT_FOLIO, oUT_RETORNO);
        }
    
        public virtual int PKG_RECAUDACIONES_SECUENCIA_PAGODEUDA(ObjectParameter oUT_FOLIO, ObjectParameter oUT_RETORNO)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PKG_RECAUDACIONES_SECUENCIA_PAGODEUDA", oUT_FOLIO, oUT_RETORNO);
        }
    
        public virtual int PKG_RECAUDACIONES_SP_ACT_AGENCIA(Nullable<decimal> iN_AGENCIA, Nullable<decimal> iN_FOLIOPAGO, ObjectParameter oUT_RETORNO)
        {
            var iN_AGENCIAParameter = iN_AGENCIA.HasValue ?
                new ObjectParameter("IN_AGENCIA", iN_AGENCIA) :
                new ObjectParameter("IN_AGENCIA", typeof(decimal));
    
            var iN_FOLIOPAGOParameter = iN_FOLIOPAGO.HasValue ?
                new ObjectParameter("IN_FOLIOPAGO", iN_FOLIOPAGO) :
                new ObjectParameter("IN_FOLIOPAGO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PKG_RECAUDACIONES_SP_ACT_AGENCIA", iN_AGENCIAParameter, iN_FOLIOPAGOParameter, oUT_RETORNO);
        }
    }
}
