//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PagosWebEntities : DbContext
    {
        public PagosWebEntities()
            : base("name=PagosWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<PagoWebEntity> PKG_CONSULTAS_WEB_BUSCAR_PAGO_TEST(Nullable<decimal> iDFOLIO, Nullable<decimal> rUT, Nullable<decimal> mONTO, Nullable<decimal> eSTADO, string fECHADESDE, string fECHAHASTA, string tIPO_PAGO, Nullable<decimal> mEDIO_PAGO, Nullable<decimal> iSAPRE, ObjectParameter eXCEPT_TEXT)
        {
            var iDFOLIOParameter = iDFOLIO.HasValue ?
                new ObjectParameter("IDFOLIO", iDFOLIO) :
                new ObjectParameter("IDFOLIO", typeof(decimal));
    
            var rUTParameter = rUT.HasValue ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(decimal));
    
            var mONTOParameter = mONTO.HasValue ?
                new ObjectParameter("MONTO", mONTO) :
                new ObjectParameter("MONTO", typeof(decimal));
    
            var eSTADOParameter = eSTADO.HasValue ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(decimal));
    
            var fECHADESDEParameter = fECHADESDE != null ?
                new ObjectParameter("FECHADESDE", fECHADESDE) :
                new ObjectParameter("FECHADESDE", typeof(string));
    
            var fECHAHASTAParameter = fECHAHASTA != null ?
                new ObjectParameter("FECHAHASTA", fECHAHASTA) :
                new ObjectParameter("FECHAHASTA", typeof(string));
    
            var tIPO_PAGOParameter = tIPO_PAGO != null ?
                new ObjectParameter("TIPO_PAGO", tIPO_PAGO) :
                new ObjectParameter("TIPO_PAGO", typeof(string));
    
            var mEDIO_PAGOParameter = mEDIO_PAGO.HasValue ?
                new ObjectParameter("MEDIO_PAGO", mEDIO_PAGO) :
                new ObjectParameter("MEDIO_PAGO", typeof(decimal));
    
            var iSAPREParameter = iSAPRE.HasValue ?
                new ObjectParameter("ISAPRE", iSAPRE) :
                new ObjectParameter("ISAPRE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PagoWebEntity>("PKG_CONSULTAS_WEB_BUSCAR_PAGO_TEST", iDFOLIOParameter, rUTParameter, mONTOParameter, eSTADOParameter, fECHADESDEParameter, fECHAHASTAParameter, tIPO_PAGOParameter, mEDIO_PAGOParameter, iSAPREParameter, eXCEPT_TEXT);
        }
    
        public virtual ObjectResult<PagoRutEntity> PKG_CONSULTAS_WEB_BUSCAR_PAGO_RUT(Nullable<decimal> rUTPAGO, ObjectParameter eXCEPT_TEXT)
        {
            var rUTPAGOParameter = rUTPAGO.HasValue ?
                new ObjectParameter("RUTPAGO", rUTPAGO) :
                new ObjectParameter("RUTPAGO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PagoRutEntity>("PKG_CONSULTAS_WEB_BUSCAR_PAGO_RUT", rUTPAGOParameter, eXCEPT_TEXT);
        }
    
        public virtual int PKG_CONSULTAS_WEB_REGULARIZAR_PAGO_TEST(Nullable<decimal> rUT, Nullable<decimal> i_WTP_ID, ObjectParameter eXCEPT_TEXT)
        {
            var rUTParameter = rUT.HasValue ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(decimal));
    
            var i_WTP_IDParameter = i_WTP_ID.HasValue ?
                new ObjectParameter("I_WTP_ID", i_WTP_ID) :
                new ObjectParameter("I_WTP_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PKG_CONSULTAS_WEB_REGULARIZAR_PAGO_TEST", rUTParameter, i_WTP_IDParameter, eXCEPT_TEXT);
        }
    
        public virtual ObjectResult<LlenarListaWebEntity> PKG_CONSULTAS_WEB_LLENARLISTAS(string aCCION, ObjectParameter eXCEPT_TEXT)
        {
            var aCCIONParameter = aCCION != null ?
                new ObjectParameter("ACCION", aCCION) :
                new ObjectParameter("ACCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LlenarListaWebEntity>("PKG_CONSULTAS_WEB_LLENARLISTAS", aCCIONParameter, eXCEPT_TEXT);
        }
    
        public virtual ObjectResult<DetalleDeudasEntity> PKG_CONSULTAS_WEB_DETALLES_DEUDAS(Nullable<decimal> pERIODO, ObjectParameter eXCEPT_TEXT)
        {
            var pERIODOParameter = pERIODO.HasValue ?
                new ObjectParameter("PERIODO", pERIODO) :
                new ObjectParameter("PERIODO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetalleDeudasEntity>("PKG_CONSULTAS_WEB_DETALLES_DEUDAS", pERIODOParameter, eXCEPT_TEXT);
        }
    }
}
