//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    
    public partial class CargasLogEntity
    {
        public decimal CARG_CCORR { get; set; }
        public string CARG_TNOMBRES { get; set; }
        public string CARG_TAPELLIDO_PATERNO { get; set; }
        public string CARG_TAPELLIDO_MATERNO { get; set; }
        public Nullable<decimal> CARG_NRUT { get; set; }
        public string CARG_XDV { get; set; }
        public string CARG_FNACIMIENTO { get; set; }
        public string CARG_XSEXO { get; set; }
        public string PARENTESCO { get; set; }
    }
}
