//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    
    public partial class CargoNewEntity
    {
        public Nullable<decimal> PERIODO { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public string UNIDAD { get; set; }
        public Nullable<decimal> VALOR_PESOS { get; set; }
        public Nullable<System.DateTime> FECHA_REFERENCIA { get; set; }
        public Nullable<decimal> MONTO_GES { get; set; }
        public Nullable<decimal> REAJUSTE { get; set; }
        public Nullable<decimal> INTERES { get; set; }
        public Nullable<decimal> RECARGO { get; set; }
        public Nullable<decimal> VALOR_TOTAL { get; set; }
    }
}
