//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    
    public partial class CertificadoCotizaEntity
    {
        public Nullable<decimal> PERIODO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string PACTADO { get; set; }
        public string PAGADO { get; set; }
        public string DNP { get; set; }
        public string FECHAPAGO { get; set; }
        public string LICENCIA { get; set; }
    }
}
