//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ConsafilProdEntities : DbContext
    {
        public ConsafilProdEntities()
            : base("name=ConsafilProdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<CotizacionesSubsidioEntity> PKG_SUBSI_LICENCIAS_V2_SP_CERT_SUBSI_1(Nullable<decimal> pRM_RUT_AFILIADO, string pRM_ISAP_CEMPRESA, Nullable<decimal> pRM_PERINI, Nullable<decimal> pRM_PERFIN)
        {
            var pRM_RUT_AFILIADOParameter = pRM_RUT_AFILIADO.HasValue ?
                new ObjectParameter("PRM_RUT_AFILIADO", pRM_RUT_AFILIADO) :
                new ObjectParameter("PRM_RUT_AFILIADO", typeof(decimal));
    
            var pRM_ISAP_CEMPRESAParameter = pRM_ISAP_CEMPRESA != null ?
                new ObjectParameter("PRM_ISAP_CEMPRESA", pRM_ISAP_CEMPRESA) :
                new ObjectParameter("PRM_ISAP_CEMPRESA", typeof(string));
    
            var pRM_PERINIParameter = pRM_PERINI.HasValue ?
                new ObjectParameter("PRM_PERINI", pRM_PERINI) :
                new ObjectParameter("PRM_PERINI", typeof(decimal));
    
            var pRM_PERFINParameter = pRM_PERFIN.HasValue ?
                new ObjectParameter("PRM_PERFIN", pRM_PERFIN) :
                new ObjectParameter("PRM_PERFIN", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CotizacionesSubsidioEntity>("PKG_SUBSI_LICENCIAS_V2_SP_CERT_SUBSI_1", pRM_RUT_AFILIADOParameter, pRM_ISAP_CEMPRESAParameter, pRM_PERINIParameter, pRM_PERFINParameter);
        }
    
        public virtual ObjectResult<CotizacionesSubsidio2Entity> PKG_SUBSI_LICENCIAS_V2_SP_CERT_SUBSI_2(Nullable<decimal> pRM_RUT_AFILIADO, string pRM_ISAP_CEMPRESA, Nullable<decimal> pRM_PERINI, Nullable<decimal> pRM_PERFIN)
        {
            var pRM_RUT_AFILIADOParameter = pRM_RUT_AFILIADO.HasValue ?
                new ObjectParameter("PRM_RUT_AFILIADO", pRM_RUT_AFILIADO) :
                new ObjectParameter("PRM_RUT_AFILIADO", typeof(decimal));
    
            var pRM_ISAP_CEMPRESAParameter = pRM_ISAP_CEMPRESA != null ?
                new ObjectParameter("PRM_ISAP_CEMPRESA", pRM_ISAP_CEMPRESA) :
                new ObjectParameter("PRM_ISAP_CEMPRESA", typeof(string));
    
            var pRM_PERINIParameter = pRM_PERINI.HasValue ?
                new ObjectParameter("PRM_PERINI", pRM_PERINI) :
                new ObjectParameter("PRM_PERINI", typeof(decimal));
    
            var pRM_PERFINParameter = pRM_PERFIN.HasValue ?
                new ObjectParameter("PRM_PERFIN", pRM_PERFIN) :
                new ObjectParameter("PRM_PERFIN", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CotizacionesSubsidio2Entity>("PKG_SUBSI_LICENCIAS_V2_SP_CERT_SUBSI_2", pRM_RUT_AFILIADOParameter, pRM_ISAP_CEMPRESAParameter, pRM_PERINIParameter, pRM_PERFINParameter);
        }
    }
}
