//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Cot2000ProdEntities : DbContext
    {
        public Cot2000ProdEntities()
            : base("name=Cot2000ProdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<ReqSuperIntendenciaEntity> SP_CONSULTA_CIRCULAR164(Nullable<decimal> p_RUT, string p_ISAPRE)
        {
            var p_RUTParameter = p_RUT.HasValue ?
                new ObjectParameter("P_RUT", p_RUT) :
                new ObjectParameter("P_RUT", typeof(decimal));
    
            var p_ISAPREParameter = p_ISAPRE != null ?
                new ObjectParameter("P_ISAPRE", p_ISAPRE) :
                new ObjectParameter("P_ISAPRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReqSuperIntendenciaEntity>("SP_CONSULTA_CIRCULAR164", p_RUTParameter, p_ISAPREParameter);
        }
    }
}
