//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    
    public partial class CotizacionesSubsidio2Entity
    {
        public string NOMAFIL { get; set; }
        public Nullable<decimal> LICENCIA { get; set; }
        public decimal RUTAFIL { get; set; }
        public System.DateTime SUBS_FPAGO { get; set; }
        public Nullable<decimal> SUBSIDIO { get; set; }
        public string FINICIO { get; set; }
        public string FFINAL { get; set; }
        public Nullable<decimal> DIAS { get; set; }
        public Nullable<decimal> RENTA { get; set; }
        public decimal CASU_MRENTA_PROMEDIO { get; set; }
        public Nullable<decimal> TRABAJADOR { get; set; }
    }
}
