//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    
    public partial class CotizacionesSubsidioEntity
    {
        public string NOMAFIL { get; set; }
        public Nullable<decimal> LICENCIA { get; set; }
        public Nullable<decimal> RUTAFIL { get; set; }
        public Nullable<decimal> DIAS { get; set; }
        public string CAFP { get; set; }
        public string PACO_FINICIO { get; set; }
        public string PACO_FFINAL { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public Nullable<decimal> SALUD { get; set; }
        public Nullable<decimal> IMPONIBLE { get; set; }
        public Nullable<decimal> TRABAJADOR { get; set; }
        public Nullable<decimal> PREVISION { get; set; }
        public Nullable<decimal> NCAJAP { get; set; }
        public string CCAJAP { get; set; }
        public Nullable<decimal> MCESANTIA { get; set; }
        public Nullable<System.DateTime> PACO_FINICIO_ORDEN { get; set; }
    }
}
