//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    
    public partial class CotizacionEntity
    {
        public string PER_COTIZ_N { get; set; }
        public string F_VENCIM_N { get; set; }
        public string COTIZ_PACTADA_N { get; set; }
        public string F_UF_N { get; set; }
        public string CALLE { get; set; }
        public string NUMERO { get; set; }
        public string BLOCK { get; set; }
        public string DEPTO { get; set; }
        public string VILLA { get; set; }
        public string AFIL_TNOMBRES { get; set; }
        public string AFIL_TAPELLIDO_PATERNO { get; set; }
        public string AFIL_TAPELLIDO_MATERNO { get; set; }
        public string AFIL_NRUT { get; set; }
        public string CIUDAD { get; set; }
        public string COMUNA { get; set; }
        public string PLSA_CCD { get; set; }
        public string SEC { get; set; }
        public string TITR_CCOD { get; set; }
    }
}
