//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    
    public partial class DatosAfiliadoEntity
    {
        public string TNOMBRES { get; set; }
        public string AFIL_TCALLE { get; set; }
        public string AFIL_TNUMERO { get; set; }
        public string AFIL_TDEPTO { get; set; }
        public string AFIL_TBLOCK { get; set; }
        public string AFIL_TVILLA { get; set; }
        public Nullable<decimal> AFIL_TFONO1 { get; set; }
        public decimal AFIL_NRUT { get; set; }
        public string AFIL_XDV { get; set; }
        public string AFIL_FNACIMIENTO { get; set; }
        public string LOCA_TNOMBRE_COMUNA { get; set; }
        public string LOCA_TNOMBRE_CIUDAD { get; set; }
        public string PLSA_CCOD { get; set; }
        public Nullable<decimal> AFIL_MCOTIZACION_TOTAL { get; set; }
        public Nullable<decimal> AFIL_XSEXO { get; set; }
        public Nullable<decimal> AFIL_XESTADO_CIVIL { get; set; }
        public Nullable<decimal> AFIL_TFONO2 { get; set; }
        public Nullable<decimal> AFIL_TFONO_CELULAR { get; set; }
        public string AFIL_TEMAIL { get; set; }
        public Nullable<decimal> LOCA_CREGION { get; set; }
        public string AFIL_FINGRESO_ISAPRE { get; set; }
        public Nullable<decimal> AFIL_LNUM_CONTRATO { get; set; }
    }
}
