//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    
    public partial class DetalleDeudaEntity
    {
        public decimal PERIODO { get; set; }
        public decimal SPRODUCTO { get; set; }
        public string GLOSA_SPRODUCTO { get; set; }
        public Nullable<decimal> DEUDA { get; set; }
        public Nullable<decimal> REAJUSTE { get; set; }
        public Nullable<decimal> INTERES { get; set; }
        public Nullable<decimal> RECARGO { get; set; }
        public Nullable<decimal> GASTOS { get; set; }
        public decimal SUBPRODUCTO { get; set; }
    }
}
