//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    
    public partial class DetalleExcedenteEntity
    {
        public string CAEX_PREMUN { get; set; }
        public Nullable<decimal> CAEX_MEXCEDENTE { get; set; }
        public Nullable<decimal> CAEX_MREAJUSTE { get; set; }
        public Nullable<decimal> CAEX_MINTERES { get; set; }
        public Nullable<decimal> CAEX_MCOMISION { get; set; }
        public Nullable<decimal> CAEX_MSALDO { get; set; }
        public Nullable<decimal> CAEX_MDISPONIBLE { get; set; }
        public Nullable<decimal> CAEX_MUSO { get; set; }
    }
}
