//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    
    public partial class DetalleDeudasEntity
    {
        public Nullable<decimal> FOLIOPAGO { get; set; }
        public Nullable<decimal> REMUN { get; set; }
        public Nullable<decimal> SUBPRODUCTO { get; set; }
        public Nullable<decimal> DEUDA { get; set; }
        public Nullable<decimal> REAJUSTE { get; set; }
        public Nullable<decimal> INTERESES { get; set; }
        public Nullable<decimal> RECARGO { get; set; }
        public Nullable<decimal> HONORARIOS { get; set; }
        public Nullable<decimal> PAGOTOTAL { get; set; }
    }
}
