//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    
    public partial class DetallePagoEntity
    {
        public string NOMBRE { get; set; }
        public decimal AFIL_NRUT { get; set; }
        public string ISAP_CEMPRESA { get; set; }
        public decimal FOLIO_PAGO { get; set; }
        public string TIPO { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO { get; set; }
        public string FORMA_PAGO { get; set; }
        public string MAIL { get; set; }
        public Nullable<decimal> MGASTOCOB_TOTAL { get; set; }
        public decimal MPAGO_TOTAL { get; set; }
        public Nullable<decimal> MDEUDA { get; set; }
        public Nullable<decimal> MGASTOCOB { get; set; }
        public Nullable<decimal> MHONORARIO { get; set; }
        public Nullable<decimal> MINTERES { get; set; }
        public decimal MPAGO { get; set; }
        public Nullable<decimal> MREAJUSTE { get; set; }
        public Nullable<decimal> MRECARGO { get; set; }
        public Nullable<decimal> PERIODO_RECAU { get; set; }
        public Nullable<decimal> PERIODO_REMUN { get; set; }
        public Nullable<decimal> SUBPRODUCTO { get; set; }
    }
}
