//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    
    public partial class DetCotizacionesEntity
    {
        public Nullable<decimal> ENPA_RUT { get; set; }
        public string EMPL_TNOMBRE_RAZON_SOCIAL { get; set; }
        public string ABON_PEREM { get; set; }
        public string ABON_FECPAG { get; set; }
        public Nullable<decimal> ABON_VALOR { get; set; }
    }
}
