//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    
    public partial class DocumentoEntity
    {
        public string RUT { get; set; }
        public string SOCIEDAD { get; set; }
        public string ID_MAESTRO { get; set; }
        public string CUENTA { get; set; }
        public string DOCUMENTO { get; set; }
        public string FECHA_DOC { get; set; }
        public string CLASE_DOC { get; set; }
        public string DOC_PAGO { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public string ESTADO { get; set; }
        public string MOTIVO_GIRO { get; set; }
        public decimal POSICION { get; set; }
        public string GLOSA_TIPO_DOCUMENTO { get; set; }
        public string GLOSA_ESTADO { get; set; }
        public Nullable<decimal> FORMA_REVALIDACION { get; set; }
    }
}
