//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EmpleadorEntities : DbContext
    {
        public EmpleadorEntities()
            : base("name=EmpleadorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<AfiliadoCertificadoEntity> PKG_EMPLEADORES_CERTIFICADOS_PRC_OBTIENE_AFILIADOS(Nullable<decimal> pR_EMPL_NRUT, string pR_ISAP_CEMPRESA, ObjectParameter oUT_MENSAJEERROR)
        {
            var pR_EMPL_NRUTParameter = pR_EMPL_NRUT.HasValue ?
                new ObjectParameter("PR_EMPL_NRUT", pR_EMPL_NRUT) :
                new ObjectParameter("PR_EMPL_NRUT", typeof(decimal));
    
            var pR_ISAP_CEMPRESAParameter = pR_ISAP_CEMPRESA != null ?
                new ObjectParameter("PR_ISAP_CEMPRESA", pR_ISAP_CEMPRESA) :
                new ObjectParameter("PR_ISAP_CEMPRESA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AfiliadoCertificadoEntity>("PKG_EMPLEADORES_CERTIFICADOS_PRC_OBTIENE_AFILIADOS", pR_EMPL_NRUTParameter, pR_ISAP_CEMPRESAParameter, oUT_MENSAJEERROR);
        }
    
        public virtual ObjectResult<AfiliadoCertificadoEntity> PKG_EMPLEADORES_CERTIFICADOS_PRC_OBTIENE_AFILIADO_COTIZA(Nullable<decimal> pR_EMPL_NRUT, Nullable<decimal> pR_AFIL_NRUT, string pR_ISAP_CEMPRESA, ObjectParameter oUT_MENSAJEERROR)
        {
            var pR_EMPL_NRUTParameter = pR_EMPL_NRUT.HasValue ?
                new ObjectParameter("PR_EMPL_NRUT", pR_EMPL_NRUT) :
                new ObjectParameter("PR_EMPL_NRUT", typeof(decimal));
    
            var pR_AFIL_NRUTParameter = pR_AFIL_NRUT.HasValue ?
                new ObjectParameter("PR_AFIL_NRUT", pR_AFIL_NRUT) :
                new ObjectParameter("PR_AFIL_NRUT", typeof(decimal));
    
            var pR_ISAP_CEMPRESAParameter = pR_ISAP_CEMPRESA != null ?
                new ObjectParameter("PR_ISAP_CEMPRESA", pR_ISAP_CEMPRESA) :
                new ObjectParameter("PR_ISAP_CEMPRESA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AfiliadoCertificadoEntity>("PKG_EMPLEADORES_CERTIFICADOS_PRC_OBTIENE_AFILIADO_COTIZA", pR_EMPL_NRUTParameter, pR_AFIL_NRUTParameter, pR_ISAP_CEMPRESAParameter, oUT_MENSAJEERROR);
        }
    
        public virtual ObjectResult<CertificadoCotizaEntity> PKG_EMPLEADORES_CERTIFICADOS_PRC_CERTIFICADO_COTIZA(Nullable<decimal> pR_EMPL_NRUT, Nullable<decimal> pR_AFIL_NRUT, string pR_ISAP_CEMPRESA, ObjectParameter oUT_MENSAJEERROR)
        {
            var pR_EMPL_NRUTParameter = pR_EMPL_NRUT.HasValue ?
                new ObjectParameter("PR_EMPL_NRUT", pR_EMPL_NRUT) :
                new ObjectParameter("PR_EMPL_NRUT", typeof(decimal));
    
            var pR_AFIL_NRUTParameter = pR_AFIL_NRUT.HasValue ?
                new ObjectParameter("PR_AFIL_NRUT", pR_AFIL_NRUT) :
                new ObjectParameter("PR_AFIL_NRUT", typeof(decimal));
    
            var pR_ISAP_CEMPRESAParameter = pR_ISAP_CEMPRESA != null ?
                new ObjectParameter("PR_ISAP_CEMPRESA", pR_ISAP_CEMPRESA) :
                new ObjectParameter("PR_ISAP_CEMPRESA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CertificadoCotizaEntity>("PKG_EMPLEADORES_CERTIFICADOS_PRC_CERTIFICADO_COTIZA", pR_EMPL_NRUTParameter, pR_AFIL_NRUTParameter, pR_ISAP_CEMPRESAParameter, oUT_MENSAJEERROR);
        }
    }
}
