//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IsaWebContEntities : DbContext
    {
        public IsaWebContEntities()
            : base("name=IsaWebContEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<DocumentoEntity> PKG_CIRC_EXCESO_DOCUMENTOS_PRC_DOCUMENTOS_PENDIENTES(Nullable<decimal> p_AFIL_NRUT, string p_ISAPRE, string p_CANAL)
        {
            var p_AFIL_NRUTParameter = p_AFIL_NRUT.HasValue ?
                new ObjectParameter("P_AFIL_NRUT", p_AFIL_NRUT) :
                new ObjectParameter("P_AFIL_NRUT", typeof(decimal));
    
            var p_ISAPREParameter = p_ISAPRE != null ?
                new ObjectParameter("P_ISAPRE", p_ISAPRE) :
                new ObjectParameter("P_ISAPRE", typeof(string));
    
            var p_CANALParameter = p_CANAL != null ?
                new ObjectParameter("P_CANAL", p_CANAL) :
                new ObjectParameter("P_CANAL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocumentoEntity>("PKG_CIRC_EXCESO_DOCUMENTOS_PRC_DOCUMENTOS_PENDIENTES", p_AFIL_NRUTParameter, p_ISAPREParameter, p_CANALParameter);
        }
    
        public virtual int PKG_CIRC_EXCESO_DOCUMENTOS_PRC_ACTIVAR_DOCUMENTOS(string p_RUT_DV, string p_SOCIEDAD, string p_ID_MAESTRO, string p_CUENTA, string p_DOCUMENTO, string p_FECHA_DOC, string p_CLASE_DOC, string p_DOC_PAGO, string p_VALOR, string p_ESTADO, string p_MOTIVO_GIRO, string p_POSICION, string p_CANAL, string p_FORMA_PAGO, Nullable<decimal> p_AGENCIA_DESTINO, string p_CTACTE_NUMERO, string p_CTACTE_TIPO, string p_CTACTE_BANCO, string p_FORMA_REVALIDACION, ObjectParameter p_CODIGO_ERROR, ObjectParameter p_TEXTO)
        {
            var p_RUT_DVParameter = p_RUT_DV != null ?
                new ObjectParameter("P_RUT_DV", p_RUT_DV) :
                new ObjectParameter("P_RUT_DV", typeof(string));
    
            var p_SOCIEDADParameter = p_SOCIEDAD != null ?
                new ObjectParameter("P_SOCIEDAD", p_SOCIEDAD) :
                new ObjectParameter("P_SOCIEDAD", typeof(string));
    
            var p_ID_MAESTROParameter = p_ID_MAESTRO != null ?
                new ObjectParameter("P_ID_MAESTRO", p_ID_MAESTRO) :
                new ObjectParameter("P_ID_MAESTRO", typeof(string));
    
            var p_CUENTAParameter = p_CUENTA != null ?
                new ObjectParameter("P_CUENTA", p_CUENTA) :
                new ObjectParameter("P_CUENTA", typeof(string));
    
            var p_DOCUMENTOParameter = p_DOCUMENTO != null ?
                new ObjectParameter("P_DOCUMENTO", p_DOCUMENTO) :
                new ObjectParameter("P_DOCUMENTO", typeof(string));
    
            var p_FECHA_DOCParameter = p_FECHA_DOC != null ?
                new ObjectParameter("P_FECHA_DOC", p_FECHA_DOC) :
                new ObjectParameter("P_FECHA_DOC", typeof(string));
    
            var p_CLASE_DOCParameter = p_CLASE_DOC != null ?
                new ObjectParameter("P_CLASE_DOC", p_CLASE_DOC) :
                new ObjectParameter("P_CLASE_DOC", typeof(string));
    
            var p_DOC_PAGOParameter = p_DOC_PAGO != null ?
                new ObjectParameter("P_DOC_PAGO", p_DOC_PAGO) :
                new ObjectParameter("P_DOC_PAGO", typeof(string));
    
            var p_VALORParameter = p_VALOR != null ?
                new ObjectParameter("P_VALOR", p_VALOR) :
                new ObjectParameter("P_VALOR", typeof(string));
    
            var p_ESTADOParameter = p_ESTADO != null ?
                new ObjectParameter("P_ESTADO", p_ESTADO) :
                new ObjectParameter("P_ESTADO", typeof(string));
    
            var p_MOTIVO_GIROParameter = p_MOTIVO_GIRO != null ?
                new ObjectParameter("P_MOTIVO_GIRO", p_MOTIVO_GIRO) :
                new ObjectParameter("P_MOTIVO_GIRO", typeof(string));
    
            var p_POSICIONParameter = p_POSICION != null ?
                new ObjectParameter("P_POSICION", p_POSICION) :
                new ObjectParameter("P_POSICION", typeof(string));
    
            var p_CANALParameter = p_CANAL != null ?
                new ObjectParameter("P_CANAL", p_CANAL) :
                new ObjectParameter("P_CANAL", typeof(string));
    
            var p_FORMA_PAGOParameter = p_FORMA_PAGO != null ?
                new ObjectParameter("P_FORMA_PAGO", p_FORMA_PAGO) :
                new ObjectParameter("P_FORMA_PAGO", typeof(string));
    
            var p_AGENCIA_DESTINOParameter = p_AGENCIA_DESTINO.HasValue ?
                new ObjectParameter("P_AGENCIA_DESTINO", p_AGENCIA_DESTINO) :
                new ObjectParameter("P_AGENCIA_DESTINO", typeof(decimal));
    
            var p_CTACTE_NUMEROParameter = p_CTACTE_NUMERO != null ?
                new ObjectParameter("P_CTACTE_NUMERO", p_CTACTE_NUMERO) :
                new ObjectParameter("P_CTACTE_NUMERO", typeof(string));
    
            var p_CTACTE_TIPOParameter = p_CTACTE_TIPO != null ?
                new ObjectParameter("P_CTACTE_TIPO", p_CTACTE_TIPO) :
                new ObjectParameter("P_CTACTE_TIPO", typeof(string));
    
            var p_CTACTE_BANCOParameter = p_CTACTE_BANCO != null ?
                new ObjectParameter("P_CTACTE_BANCO", p_CTACTE_BANCO) :
                new ObjectParameter("P_CTACTE_BANCO", typeof(string));
    
            var p_FORMA_REVALIDACIONParameter = p_FORMA_REVALIDACION != null ?
                new ObjectParameter("P_FORMA_REVALIDACION", p_FORMA_REVALIDACION) :
                new ObjectParameter("P_FORMA_REVALIDACION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PKG_CIRC_EXCESO_DOCUMENTOS_PRC_ACTIVAR_DOCUMENTOS", p_RUT_DVParameter, p_SOCIEDADParameter, p_ID_MAESTROParameter, p_CUENTAParameter, p_DOCUMENTOParameter, p_FECHA_DOCParameter, p_CLASE_DOCParameter, p_DOC_PAGOParameter, p_VALORParameter, p_ESTADOParameter, p_MOTIVO_GIROParameter, p_POSICIONParameter, p_CANALParameter, p_FORMA_PAGOParameter, p_AGENCIA_DESTINOParameter, p_CTACTE_NUMEROParameter, p_CTACTE_TIPOParameter, p_CTACTE_BANCOParameter, p_FORMA_REVALIDACIONParameter, p_CODIGO_ERROR, p_TEXTO);
        }
    
        public virtual int PKG_CIRC_EXCESO_DOCUMENTOS_PRC_ACTIVAR_DOCUMENTOSSAP(string p_RUT_DV, string p_SOCIEDAD, string p_ID_MAESTRO, string p_CUENTA, string p_DOCUMENTO, string p_FECHA_DOC, string p_CLASE_DOC, string p_DOC_PAGO, string p_VALOR, string p_ESTADO, string p_MOTIVO_GIRO, string p_POSICION, string p_CANAL, string p_FORMA_PAGO, Nullable<decimal> p_AGENCIA_DESTINO, string p_CTACTE_NUMERO, string p_CTACTE_TIPO, string p_CTACTE_BANCO, string p_FORMA_REVALIDACION, ObjectParameter p_CODIGO_ERROR, ObjectParameter p_TEXTO)
        {
            var p_RUT_DVParameter = p_RUT_DV != null ?
                new ObjectParameter("P_RUT_DV", p_RUT_DV) :
                new ObjectParameter("P_RUT_DV", typeof(string));
    
            var p_SOCIEDADParameter = p_SOCIEDAD != null ?
                new ObjectParameter("P_SOCIEDAD", p_SOCIEDAD) :
                new ObjectParameter("P_SOCIEDAD", typeof(string));
    
            var p_ID_MAESTROParameter = p_ID_MAESTRO != null ?
                new ObjectParameter("P_ID_MAESTRO", p_ID_MAESTRO) :
                new ObjectParameter("P_ID_MAESTRO", typeof(string));
    
            var p_CUENTAParameter = p_CUENTA != null ?
                new ObjectParameter("P_CUENTA", p_CUENTA) :
                new ObjectParameter("P_CUENTA", typeof(string));
    
            var p_DOCUMENTOParameter = p_DOCUMENTO != null ?
                new ObjectParameter("P_DOCUMENTO", p_DOCUMENTO) :
                new ObjectParameter("P_DOCUMENTO", typeof(string));
    
            var p_FECHA_DOCParameter = p_FECHA_DOC != null ?
                new ObjectParameter("P_FECHA_DOC", p_FECHA_DOC) :
                new ObjectParameter("P_FECHA_DOC", typeof(string));
    
            var p_CLASE_DOCParameter = p_CLASE_DOC != null ?
                new ObjectParameter("P_CLASE_DOC", p_CLASE_DOC) :
                new ObjectParameter("P_CLASE_DOC", typeof(string));
    
            var p_DOC_PAGOParameter = p_DOC_PAGO != null ?
                new ObjectParameter("P_DOC_PAGO", p_DOC_PAGO) :
                new ObjectParameter("P_DOC_PAGO", typeof(string));
    
            var p_VALORParameter = p_VALOR != null ?
                new ObjectParameter("P_VALOR", p_VALOR) :
                new ObjectParameter("P_VALOR", typeof(string));
    
            var p_ESTADOParameter = p_ESTADO != null ?
                new ObjectParameter("P_ESTADO", p_ESTADO) :
                new ObjectParameter("P_ESTADO", typeof(string));
    
            var p_MOTIVO_GIROParameter = p_MOTIVO_GIRO != null ?
                new ObjectParameter("P_MOTIVO_GIRO", p_MOTIVO_GIRO) :
                new ObjectParameter("P_MOTIVO_GIRO", typeof(string));
    
            var p_POSICIONParameter = p_POSICION != null ?
                new ObjectParameter("P_POSICION", p_POSICION) :
                new ObjectParameter("P_POSICION", typeof(string));
    
            var p_CANALParameter = p_CANAL != null ?
                new ObjectParameter("P_CANAL", p_CANAL) :
                new ObjectParameter("P_CANAL", typeof(string));
    
            var p_FORMA_PAGOParameter = p_FORMA_PAGO != null ?
                new ObjectParameter("P_FORMA_PAGO", p_FORMA_PAGO) :
                new ObjectParameter("P_FORMA_PAGO", typeof(string));
    
            var p_AGENCIA_DESTINOParameter = p_AGENCIA_DESTINO.HasValue ?
                new ObjectParameter("P_AGENCIA_DESTINO", p_AGENCIA_DESTINO) :
                new ObjectParameter("P_AGENCIA_DESTINO", typeof(decimal));
    
            var p_CTACTE_NUMEROParameter = p_CTACTE_NUMERO != null ?
                new ObjectParameter("P_CTACTE_NUMERO", p_CTACTE_NUMERO) :
                new ObjectParameter("P_CTACTE_NUMERO", typeof(string));
    
            var p_CTACTE_TIPOParameter = p_CTACTE_TIPO != null ?
                new ObjectParameter("P_CTACTE_TIPO", p_CTACTE_TIPO) :
                new ObjectParameter("P_CTACTE_TIPO", typeof(string));
    
            var p_CTACTE_BANCOParameter = p_CTACTE_BANCO != null ?
                new ObjectParameter("P_CTACTE_BANCO", p_CTACTE_BANCO) :
                new ObjectParameter("P_CTACTE_BANCO", typeof(string));
    
            var p_FORMA_REVALIDACIONParameter = p_FORMA_REVALIDACION != null ?
                new ObjectParameter("P_FORMA_REVALIDACION", p_FORMA_REVALIDACION) :
                new ObjectParameter("P_FORMA_REVALIDACION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PKG_CIRC_EXCESO_DOCUMENTOS_PRC_ACTIVAR_DOCUMENTOSSAP", p_RUT_DVParameter, p_SOCIEDADParameter, p_ID_MAESTROParameter, p_CUENTAParameter, p_DOCUMENTOParameter, p_FECHA_DOCParameter, p_CLASE_DOCParameter, p_DOC_PAGOParameter, p_VALORParameter, p_ESTADOParameter, p_MOTIVO_GIROParameter, p_POSICIONParameter, p_CANALParameter, p_FORMA_PAGOParameter, p_AGENCIA_DESTINOParameter, p_CTACTE_NUMEROParameter, p_CTACTE_TIPOParameter, p_CTACTE_BANCOParameter, p_FORMA_REVALIDACIONParameter, p_CODIGO_ERROR, p_TEXTO);
        }
    
        public virtual ObjectResult<ReqSuperIntendEntity> SP_HISTORICO_PAGOS_PUBLICO(Nullable<decimal> p_AFIL_NRUT, string p_ISAPRE, ObjectParameter p_TIPORUT, ObjectParameter p_ESTADO)
        {
            var p_AFIL_NRUTParameter = p_AFIL_NRUT.HasValue ?
                new ObjectParameter("P_AFIL_NRUT", p_AFIL_NRUT) :
                new ObjectParameter("P_AFIL_NRUT", typeof(decimal));
    
            var p_ISAPREParameter = p_ISAPRE != null ?
                new ObjectParameter("P_ISAPRE", p_ISAPRE) :
                new ObjectParameter("P_ISAPRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReqSuperIntendEntity>("SP_HISTORICO_PAGOS_PUBLICO", p_AFIL_NRUTParameter, p_ISAPREParameter, p_TIPORUT, p_ESTADO);
        }
    }
}
