//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    
    public partial class InventarioDocumentoEntity
    {
        public Nullable<decimal> FECHA_EMISION { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public Nullable<decimal> NUMERO_DOCUMENTO { get; set; }
        public Nullable<decimal> MONTO { get; set; }
    }
}
