//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    
    public partial class PagoRutEntity
    {
        public Nullable<decimal> FOLIO { get; set; }
        public Nullable<decimal> RUT { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public Nullable<decimal> ESTADO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string TIPOPAGO { get; set; }
        public Nullable<decimal> MEDIOPAGO { get; set; }
        public Nullable<decimal> ISAPRE { get; set; }
    }
}
