//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    
    public partial class PeriodoEntity
    {
        public string PCOT_PREMUN { get; set; }
        public string PCOT_FCREACION { get; set; }
        public decimal PCOT_MPAGO { get; set; }
    }
}
