//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PSucursalSucuEntities : DbContext
    {
        public PSucursalSucuEntities()
            : base("name=PSucursalSucuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int EXCEDENTE_DISPON_WEB(Nullable<decimal> p_RUT, string p_ISAPRE, ObjectParameter p_RETORNO, string p_OPCION_GLOSA, ObjectParameter p_CUENTA)
        {
            var p_RUTParameter = p_RUT.HasValue ?
                new ObjectParameter("P_RUT", p_RUT) :
                new ObjectParameter("P_RUT", typeof(decimal));
    
            var p_ISAPREParameter = p_ISAPRE != null ?
                new ObjectParameter("P_ISAPRE", p_ISAPRE) :
                new ObjectParameter("P_ISAPRE", typeof(string));
    
            var p_OPCION_GLOSAParameter = p_OPCION_GLOSA != null ?
                new ObjectParameter("P_OPCION_GLOSA", p_OPCION_GLOSA) :
                new ObjectParameter("P_OPCION_GLOSA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EXCEDENTE_DISPON_WEB", p_RUTParameter, p_ISAPREParameter, p_RETORNO, p_OPCION_GLOSAParameter, p_CUENTA);
        }
    
        public virtual int PKG_PAGO_MODULO_SP_INSERTAPAGOMODULO(Nullable<decimal> nRUTAFILIADO, string sCANAL, string sCODIGOAUT, Nullable<decimal> nDBTOTAL, Nullable<System.DateTime> dFECHACONTABLE, Nullable<System.DateTime> dFECHAPAGO, Nullable<decimal> nFOLIO, string sFORMAPAGO, string sISAPRE, string sMARCA, Nullable<decimal> nMONTO, string sNUMEROCTA, string sNUMEROTARJETA, string sNUMEROBOLETA, string sNUMEROOP, string sTERMINAL, Nullable<decimal> nTIPOPAGO, string sTIPOTARJETA, ObjectParameter nCODERROR, ObjectParameter sTEXTERROR)
        {
            var nRUTAFILIADOParameter = nRUTAFILIADO.HasValue ?
                new ObjectParameter("NRUTAFILIADO", nRUTAFILIADO) :
                new ObjectParameter("NRUTAFILIADO", typeof(decimal));
    
            var sCANALParameter = sCANAL != null ?
                new ObjectParameter("SCANAL", sCANAL) :
                new ObjectParameter("SCANAL", typeof(string));
    
            var sCODIGOAUTParameter = sCODIGOAUT != null ?
                new ObjectParameter("SCODIGOAUT", sCODIGOAUT) :
                new ObjectParameter("SCODIGOAUT", typeof(string));
    
            var nDBTOTALParameter = nDBTOTAL.HasValue ?
                new ObjectParameter("NDBTOTAL", nDBTOTAL) :
                new ObjectParameter("NDBTOTAL", typeof(decimal));
    
            var dFECHACONTABLEParameter = dFECHACONTABLE.HasValue ?
                new ObjectParameter("DFECHACONTABLE", dFECHACONTABLE) :
                new ObjectParameter("DFECHACONTABLE", typeof(System.DateTime));
    
            var dFECHAPAGOParameter = dFECHAPAGO.HasValue ?
                new ObjectParameter("DFECHAPAGO", dFECHAPAGO) :
                new ObjectParameter("DFECHAPAGO", typeof(System.DateTime));
    
            var nFOLIOParameter = nFOLIO.HasValue ?
                new ObjectParameter("NFOLIO", nFOLIO) :
                new ObjectParameter("NFOLIO", typeof(decimal));
    
            var sFORMAPAGOParameter = sFORMAPAGO != null ?
                new ObjectParameter("SFORMAPAGO", sFORMAPAGO) :
                new ObjectParameter("SFORMAPAGO", typeof(string));
    
            var sISAPREParameter = sISAPRE != null ?
                new ObjectParameter("SISAPRE", sISAPRE) :
                new ObjectParameter("SISAPRE", typeof(string));
    
            var sMARCAParameter = sMARCA != null ?
                new ObjectParameter("SMARCA", sMARCA) :
                new ObjectParameter("SMARCA", typeof(string));
    
            var nMONTOParameter = nMONTO.HasValue ?
                new ObjectParameter("NMONTO", nMONTO) :
                new ObjectParameter("NMONTO", typeof(decimal));
    
            var sNUMEROCTAParameter = sNUMEROCTA != null ?
                new ObjectParameter("SNUMEROCTA", sNUMEROCTA) :
                new ObjectParameter("SNUMEROCTA", typeof(string));
    
            var sNUMEROTARJETAParameter = sNUMEROTARJETA != null ?
                new ObjectParameter("SNUMEROTARJETA", sNUMEROTARJETA) :
                new ObjectParameter("SNUMEROTARJETA", typeof(string));
    
            var sNUMEROBOLETAParameter = sNUMEROBOLETA != null ?
                new ObjectParameter("SNUMEROBOLETA", sNUMEROBOLETA) :
                new ObjectParameter("SNUMEROBOLETA", typeof(string));
    
            var sNUMEROOPParameter = sNUMEROOP != null ?
                new ObjectParameter("SNUMEROOP", sNUMEROOP) :
                new ObjectParameter("SNUMEROOP", typeof(string));
    
            var sTERMINALParameter = sTERMINAL != null ?
                new ObjectParameter("STERMINAL", sTERMINAL) :
                new ObjectParameter("STERMINAL", typeof(string));
    
            var nTIPOPAGOParameter = nTIPOPAGO.HasValue ?
                new ObjectParameter("NTIPOPAGO", nTIPOPAGO) :
                new ObjectParameter("NTIPOPAGO", typeof(decimal));
    
            var sTIPOTARJETAParameter = sTIPOTARJETA != null ?
                new ObjectParameter("STIPOTARJETA", sTIPOTARJETA) :
                new ObjectParameter("STIPOTARJETA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PKG_PAGO_MODULO_SP_INSERTAPAGOMODULO", nRUTAFILIADOParameter, sCANALParameter, sCODIGOAUTParameter, nDBTOTALParameter, dFECHACONTABLEParameter, dFECHAPAGOParameter, nFOLIOParameter, sFORMAPAGOParameter, sISAPREParameter, sMARCAParameter, nMONTOParameter, sNUMEROCTAParameter, sNUMEROTARJETAParameter, sNUMEROBOLETAParameter, sNUMEROOPParameter, sTERMINALParameter, nTIPOPAGOParameter, sTIPOTARJETAParameter, nCODERROR, sTEXTERROR);
        }
    
        public virtual int PKG_PAGO_MODULO_PM_REGISTRA_PAGO(Nullable<decimal> nAFIL_NRUT, string sISAP_CEMPRESA, Nullable<decimal> nFOLIO, Nullable<decimal> nTIPO_PAGO, Nullable<decimal> nADMI_RUT, Nullable<decimal> nAGEN_CAGENCIA, ObjectParameter nCODERROR, ObjectParameter sTEXTERROR)
        {
            var nAFIL_NRUTParameter = nAFIL_NRUT.HasValue ?
                new ObjectParameter("NAFIL_NRUT", nAFIL_NRUT) :
                new ObjectParameter("NAFIL_NRUT", typeof(decimal));
    
            var sISAP_CEMPRESAParameter = sISAP_CEMPRESA != null ?
                new ObjectParameter("SISAP_CEMPRESA", sISAP_CEMPRESA) :
                new ObjectParameter("SISAP_CEMPRESA", typeof(string));
    
            var nFOLIOParameter = nFOLIO.HasValue ?
                new ObjectParameter("NFOLIO", nFOLIO) :
                new ObjectParameter("NFOLIO", typeof(decimal));
    
            var nTIPO_PAGOParameter = nTIPO_PAGO.HasValue ?
                new ObjectParameter("NTIPO_PAGO", nTIPO_PAGO) :
                new ObjectParameter("NTIPO_PAGO", typeof(decimal));
    
            var nADMI_RUTParameter = nADMI_RUT.HasValue ?
                new ObjectParameter("NADMI_RUT", nADMI_RUT) :
                new ObjectParameter("NADMI_RUT", typeof(decimal));
    
            var nAGEN_CAGENCIAParameter = nAGEN_CAGENCIA.HasValue ?
                new ObjectParameter("NAGEN_CAGENCIA", nAGEN_CAGENCIA) :
                new ObjectParameter("NAGEN_CAGENCIA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PKG_PAGO_MODULO_PM_REGISTRA_PAGO", nAFIL_NRUTParameter, sISAP_CEMPRESAParameter, nFOLIOParameter, nTIPO_PAGOParameter, nADMI_RUTParameter, nAGEN_CAGENCIAParameter, nCODERROR, sTEXTERROR);
        }
    }
}
