//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    
    public partial class ReqSuperIntendenciaEntity
    {
        public string TIPO_COTIZACION { get; set; }
        public string RUT { get; set; }
        public string PERIODO { get; set; }
        public string ESTADO { get; set; }
        public string NOMBRE_ASEGURADORA { get; set; }
        public Nullable<decimal> DESO_PERREMUN_AO { get; set; }
    }
}
