//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Models.Entities
{
    using System;
    
    public partial class ReqSuperIntendEntity
    {
        public Nullable<decimal> AFIL_NRUT { get; set; }
        public string ISAP_CEMPRESA { get; set; }
        public string FECHA_EMISION { get; set; }
        public string MOTIVO { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public string FORMA_PAGO { get; set; }
        public decimal NUMERO_DOCUMENTO { get; set; }
        public string ESTADO { get; set; }
        public string PROC_REVALIDACION { get; set; }
        public string FECHA_EMISION_ORDER { get; set; }
        public string CHEDA_ESTADO { get; set; }
        public string PAGE_ESCALAFON { get; set; }
    }
}
