//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WS_Ingresos.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener informacion para rut empleador {0}, rut afiliado {1} e isapre {2}, revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_AfiliadoCotizaciones {
            get {
                return ResourceManager.GetString("Ex_AfiliadoCotizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener información de devolución de excesos para rut empleador {0} y isapre {1} revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_AfiliadosCotizaciones {
            get {
                return ResourceManager.GetString("Ex_AfiliadosCotizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener informacion para rut {0} e isapre {1}, revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_Cargas {
            get {
                return ResourceManager.GetString("Ex_Cargas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener informacion para rut {0} e isapre {1}, revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_Cotizaciones {
            get {
                return ResourceManager.GetString("Ex_Cotizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener información de devolución de excesos para rut {0} e isapre {1}, revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_Cuentas {
            get {
                return ResourceManager.GetString("Ex_Cuentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener informacion al obtener cuponera para rut {0} e isapre {1}, revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_Cuponera {
            get {
                return ResourceManager.GetString("Ex_Cuponera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo grabar los datos para rut {0}, periodo {1}, periodoAnt {2}, valorPesos {3}, fechaRef {4}, fechaCreacion {5}, estado {6}, empresa {7}, reajuste {8}, interes {9}, recargo {10}, total {11}, folio {12} e IdPagoByte {13}, revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_DatosCotizaNew {
            get {
                return ResourceManager.GetString("Ex_DatosCotizaNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener informacion para rut {0} e isapre {1}, revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_Deudas {
            get {
                return ResourceManager.GetString("Ex_Deudas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener información de devolución de excesos para rut {0}, isapre {1} y canal {2}, revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_DevolucionExcesos {
            get {
                return ResourceManager.GetString("Ex_DevolucionExcesos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener información de detalle excesos registro individual para rut {0}, isapre {1} y canal {2}, revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_DevolucionExcesosRI {
            get {
                return ResourceManager.GetString("Ex_DevolucionExcesosRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener información de documentos pendientes de cobro para rut {0}, isapre {1} y canal {2}, revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_Documento {
            get {
                return ResourceManager.GetString("Ex_Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener folio, revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_Folio {
            get {
                return ResourceManager.GetString("Ex_Folio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo generar planilla de pago de tipo {0} para rut {1} e isapre {2}, revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_GeneraPlanilla {
            get {
                return ResourceManager.GetString("Ex_GeneraPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener informacion para rut {0} e isapre {1}, revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_GetDatosAfiliado {
            get {
                return ResourceManager.GetString("Ex_GetDatosAfiliado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener informacion para rut {0} e isapre {1}, revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_GetDatosEmpleadorByRutAfil {
            get {
                return ResourceManager.GetString("Ex_GetDatosEmpleadorByRutAfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener informacion para rut {0} e isapre {1}, revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_GetDatosEmpleadorByRutEmpl {
            get {
                return ResourceManager.GetString("Ex_GetDatosEmpleadorByRutEmpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener informacion para rut {0} e isapre {1}, revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_GetDetalleCotizaciones {
            get {
                return ResourceManager.GetString("Ex_GetDetalleCotizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener información al obtener detalle deuda para rut {0} e isapre {1} revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_GetDetalleDeuda {
            get {
                return ResourceManager.GetString("Ex_GetDetalleDeuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener información de folios de negociación para rut {0} e isapre {1} revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_GetFoliosNegociacion {
            get {
                return ResourceManager.GetString("Ex_GetFoliosNegociacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo pagar planilla con folio {0} para rut {1}, isapre {2} y agencia {3}, revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_PagoPlanilla {
            get {
                return ResourceManager.GetString("Ex_PagoPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener información de documentos de cobro pendiente para isapre {0} y rut {1}, revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_ReqSuperIntend {
            get {
                return ResourceManager.GetString("Ex_ReqSuperIntend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener información de requerimientos de superintendencia para isapre {0} y rut {1}, revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_ReqSuperIntendencia {
            get {
                return ResourceManager.GetString("Ex_ReqSuperIntendencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener informacion al obtener cuponera para rut {0}, isapre {1} y tipo {2} revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_SaldoExcedentes {
            get {
                return ResourceManager.GetString("Ex_SaldoExcedentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener informacion, revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_SecuenciaDeuda {
            get {
                return ResourceManager.GetString("Ex_SecuenciaDeuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo grabar el requerimiento de solicitud de excesos para rut {0} e isapre {1}, revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_SolicitudDevolucionExcesos {
            get {
                return ResourceManager.GetString("Ex_SolicitudDevolucionExcesos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo grabar la(s) solicitudud(es) de reemision, revise el archivo de log para obtener más información..
        /// </summary>
        internal static string Ex_SolicitudReemision {
            get {
                return ResourceManager.GetString("Ex_SolicitudReemision", resourceCulture);
            }
        }
    }
}
