//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Ingresos.PlanillasServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas", ConfigurationName="PlanillasServices.PlanillasSoap")]
    public interface PlanillasSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas/PagarPlanillas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool PagarPlanillas(long folio, string isapre, string formapago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas/PagarPlanillas", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> PagarPlanillasAsync(long folio, string isapre, string formapago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas/ObtenerPlanillasPorFolio" +
            "Pago", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Persona))]
        WS_Ingresos.PlanillasServices.Planilla ObtenerPlanillasPorFolioPago(long folio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas/ObtenerPlanillasPorFolio" +
            "Pago", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_Ingresos.PlanillasServices.Planilla> ObtenerPlanillasPorFolioPagoAsync(long folio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas/ObtenerPlanilla", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Persona))]
        WS_Ingresos.PlanillasServices.Respuesta ObtenerPlanilla(long folio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas/ObtenerPlanilla", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_Ingresos.PlanillasServices.Respuesta> ObtenerPlanillaAsync(long folio);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas")]
    public partial class Planilla : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int folioPagoField;
        
        private System.DateTime fechaPagoField;
        
        private long montoPagoEfectivoField;
        
        private EstadoPlanilla estadoField;
        
        private Isapre isapreField;
        
        private EntidadPagadora entePagadorField;
        
        private Parametro cambioInformacionField;
        
        private Usuario usuarioField;
        
        private Deudor deudorField;
        
        private Parametro agenciaPagoField;
        
        private DetallePlanilla[] detallePlanillasField;
        
        private AntecedentePagoDocumento[] antecedentesPagoField;
        
        private DetalleDocumento[] detalleDocumentosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int FolioPago {
            get {
                return this.folioPagoField;
            }
            set {
                this.folioPagoField = value;
                this.RaisePropertyChanged("FolioPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime FechaPago {
            get {
                return this.fechaPagoField;
            }
            set {
                this.fechaPagoField = value;
                this.RaisePropertyChanged("FechaPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long MontoPagoEfectivo {
            get {
                return this.montoPagoEfectivoField;
            }
            set {
                this.montoPagoEfectivoField = value;
                this.RaisePropertyChanged("MontoPagoEfectivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public EstadoPlanilla Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Isapre Isapre {
            get {
                return this.isapreField;
            }
            set {
                this.isapreField = value;
                this.RaisePropertyChanged("Isapre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public EntidadPagadora EntePagador {
            get {
                return this.entePagadorField;
            }
            set {
                this.entePagadorField = value;
                this.RaisePropertyChanged("EntePagador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Parametro CambioInformacion {
            get {
                return this.cambioInformacionField;
            }
            set {
                this.cambioInformacionField = value;
                this.RaisePropertyChanged("CambioInformacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Usuario Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Deudor Deudor {
            get {
                return this.deudorField;
            }
            set {
                this.deudorField = value;
                this.RaisePropertyChanged("Deudor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public Parametro AgenciaPago {
            get {
                return this.agenciaPagoField;
            }
            set {
                this.agenciaPagoField = value;
                this.RaisePropertyChanged("AgenciaPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        public DetallePlanilla[] DetallePlanillas {
            get {
                return this.detallePlanillasField;
            }
            set {
                this.detallePlanillasField = value;
                this.RaisePropertyChanged("DetallePlanillas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        public AntecedentePagoDocumento[] AntecedentesPago {
            get {
                return this.antecedentesPagoField;
            }
            set {
                this.antecedentesPagoField = value;
                this.RaisePropertyChanged("AntecedentesPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        public DetalleDocumento[] DetalleDocumentos {
            get {
                return this.detalleDocumentosField;
            }
            set {
                this.detalleDocumentosField = value;
                this.RaisePropertyChanged("DetalleDocumentos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas")]
    public enum EstadoPlanilla {
        
        /// <remarks/>
        Generada,
        
        /// <remarks/>
        Pagada,
        
        /// <remarks/>
        Anulada,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas")]
    public enum Isapre {
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        T,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas")]
    public partial class EntidadPagadora : Persona {
        
        private Direccion[] direccionesField;
        
        private RepresentanteLegal representanteLegalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Direccion[] Direcciones {
            get {
                return this.direccionesField;
            }
            set {
                this.direccionesField = value;
                this.RaisePropertyChanged("Direcciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RepresentanteLegal RepresentanteLegal {
            get {
                return this.representanteLegalField;
            }
            set {
                this.representanteLegalField = value;
                this.RaisePropertyChanged("RepresentanteLegal");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas")]
    public partial class Direccion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string calleField;
        
        private string comunaField;
        
        private string ciudadField;
        
        private string regionField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Calle {
            get {
                return this.calleField;
            }
            set {
                this.calleField = value;
                this.RaisePropertyChanged("Calle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Comuna {
            get {
                return this.comunaField;
            }
            set {
                this.comunaField = value;
                this.RaisePropertyChanged("Comuna");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
                this.RaisePropertyChanged("Ciudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("Region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas")]
    public partial class Estado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoErrorField;
        
        private string glosaErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CodigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
                this.RaisePropertyChanged("CodigoError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GlosaError {
            get {
                return this.glosaErrorField;
            }
            set {
                this.glosaErrorField = value;
                this.RaisePropertyChanged("GlosaError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas")]
    public partial class Respuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Estado estadoField;
        
        private byte[] planillaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Estado Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] Planilla {
            get {
                return this.planillaField;
            }
            set {
                this.planillaField = value;
                this.RaisePropertyChanged("Planilla");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas")]
    public partial class DetalleDocumento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Parametro bancoField;
        
        private string cuentaField;
        
        private string serieField;
        
        private string numeroDocumentoField;
        
        private long montoDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Parametro Banco {
            get {
                return this.bancoField;
            }
            set {
                this.bancoField = value;
                this.RaisePropertyChanged("Banco");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
                this.RaisePropertyChanged("Cuenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
                this.RaisePropertyChanged("Serie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NumeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
                this.RaisePropertyChanged("NumeroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long MontoDocumento {
            get {
                return this.montoDocumentoField;
            }
            set {
                this.montoDocumentoField = value;
                this.RaisePropertyChanged("MontoDocumento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas")]
    public partial class Parametro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string nombreField;
        
        private string nemotecnicoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Nemotecnico {
            get {
                return this.nemotecnicoField;
            }
            set {
                this.nemotecnicoField = value;
                this.RaisePropertyChanged("Nemotecnico");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas")]
    public partial class AntecedentePagoDocumento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TipoPeriodo tipoPeriodoField;
        
        private int cantidadField;
        
        private long montoPagoField;
        
        private decimal tasaInteresField;
        
        private long totalInteresField;
        
        private long totalPagoDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TipoPeriodo TipoPeriodo {
            get {
                return this.tipoPeriodoField;
            }
            set {
                this.tipoPeriodoField = value;
                this.RaisePropertyChanged("TipoPeriodo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("Cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long MontoPago {
            get {
                return this.montoPagoField;
            }
            set {
                this.montoPagoField = value;
                this.RaisePropertyChanged("MontoPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal TasaInteres {
            get {
                return this.tasaInteresField;
            }
            set {
                this.tasaInteresField = value;
                this.RaisePropertyChanged("TasaInteres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long TotalInteres {
            get {
                return this.totalInteresField;
            }
            set {
                this.totalInteresField = value;
                this.RaisePropertyChanged("TotalInteres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long TotalPagoDocumento {
            get {
                return this.totalPagoDocumentoField;
            }
            set {
                this.totalPagoDocumentoField = value;
                this.RaisePropertyChanged("TotalPagoDocumento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas")]
    public enum TipoPeriodo {
        
        /// <remarks/>
        Mes,
        
        /// <remarks/>
        Dia,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas")]
    public partial class DetallePlanilla : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long folioPlanillaField;
        
        private TipoPlanilla tipoPlanillaField;
        
        private TipoPagoPlanilla tipoPagoField;
        
        private TipoEntidadPagadora tipoEntidadPagadoraField;
        
        private long periodoField;
        
        private long recargoDocumentoFechaField;
        
        private int numeroAfiliadosField;
        
        private Cotizante[] cotizantesField;
        
        private System.DateTime fechaCreacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long FolioPlanilla {
            get {
                return this.folioPlanillaField;
            }
            set {
                this.folioPlanillaField = value;
                this.RaisePropertyChanged("FolioPlanilla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TipoPlanilla TipoPlanilla {
            get {
                return this.tipoPlanillaField;
            }
            set {
                this.tipoPlanillaField = value;
                this.RaisePropertyChanged("TipoPlanilla");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TipoPagoPlanilla TipoPago {
            get {
                return this.tipoPagoField;
            }
            set {
                this.tipoPagoField = value;
                this.RaisePropertyChanged("TipoPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public TipoEntidadPagadora TipoEntidadPagadora {
            get {
                return this.tipoEntidadPagadoraField;
            }
            set {
                this.tipoEntidadPagadoraField = value;
                this.RaisePropertyChanged("TipoEntidadPagadora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long Periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("Periodo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long RecargoDocumentoFecha {
            get {
                return this.recargoDocumentoFechaField;
            }
            set {
                this.recargoDocumentoFechaField = value;
                this.RaisePropertyChanged("RecargoDocumentoFecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int NumeroAfiliados {
            get {
                return this.numeroAfiliadosField;
            }
            set {
                this.numeroAfiliadosField = value;
                this.RaisePropertyChanged("NumeroAfiliados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public Cotizante[] Cotizantes {
            get {
                return this.cotizantesField;
            }
            set {
                this.cotizantesField = value;
                this.RaisePropertyChanged("Cotizantes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=8)]
        public System.DateTime FechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("FechaCreacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas")]
    public enum TipoPlanilla {
        
        /// <remarks/>
        Morosa,
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        Anticipada,
        
        /// <remarks/>
        DNP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas")]
    public enum TipoPagoPlanilla {
        
        /// <remarks/>
        DYP,
        
        /// <remarks/>
        DNP,
        
        /// <remarks/>
        Gratificacion,
        
        /// <remarks/>
        Otras,
        
        /// <remarks/>
        Voluntario,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas")]
    public enum TipoEntidadPagadora {
        
        /// <remarks/>
        Empleador,
        
        /// <remarks/>
        PagoPension,
        
        /// <remarks/>
        Independiente,
        
        /// <remarks/>
        Voluntario,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas")]
    public partial class Cotizante : Persona {
        
        private Parametro planField;
        
        private Deuda deudaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Parametro Plan {
            get {
                return this.planField;
            }
            set {
                this.planField = value;
                this.RaisePropertyChanged("Plan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Deuda Deuda {
            get {
                return this.deudaField;
            }
            set {
                this.deudaField = value;
                this.RaisePropertyChanged("Deuda");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas")]
    public partial class Deuda : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long pactadaField;
        
        private long rentaImponibleField;
        
        private long cotizacionLegalField;
        
        private long cotizacionLey18566Field;
        
        private long cotizacionVoluntariaField;
        
        private long reajusteField;
        
        private long interesField;
        
        private long recargoField;
        
        private long gastoCobranzaField;
        
        private long honorariosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Pactada {
            get {
                return this.pactadaField;
            }
            set {
                this.pactadaField = value;
                this.RaisePropertyChanged("Pactada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long RentaImponible {
            get {
                return this.rentaImponibleField;
            }
            set {
                this.rentaImponibleField = value;
                this.RaisePropertyChanged("RentaImponible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long CotizacionLegal {
            get {
                return this.cotizacionLegalField;
            }
            set {
                this.cotizacionLegalField = value;
                this.RaisePropertyChanged("CotizacionLegal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long CotizacionLey18566 {
            get {
                return this.cotizacionLey18566Field;
            }
            set {
                this.cotizacionLey18566Field = value;
                this.RaisePropertyChanged("CotizacionLey18566");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long CotizacionVoluntaria {
            get {
                return this.cotizacionVoluntariaField;
            }
            set {
                this.cotizacionVoluntariaField = value;
                this.RaisePropertyChanged("CotizacionVoluntaria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long Reajuste {
            get {
                return this.reajusteField;
            }
            set {
                this.reajusteField = value;
                this.RaisePropertyChanged("Reajuste");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long Interes {
            get {
                return this.interesField;
            }
            set {
                this.interesField = value;
                this.RaisePropertyChanged("Interes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long Recargo {
            get {
                return this.recargoField;
            }
            set {
                this.recargoField = value;
                this.RaisePropertyChanged("Recargo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long GastoCobranza {
            get {
                return this.gastoCobranzaField;
            }
            set {
                this.gastoCobranzaField = value;
                this.RaisePropertyChanged("GastoCobranza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public long Honorarios {
            get {
                return this.honorariosField;
            }
            set {
                this.honorariosField = value;
                this.RaisePropertyChanged("Honorarios");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Usuario))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Deudor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cotizante))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RepresentanteLegal))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntidadPagadora))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas")]
    public abstract partial class Persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int rutField;
        
        private string digitoVerificadorField;
        
        private string nombreField;
        
        private string apellidoPaternoField;
        
        private string apellidoMaternoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DigitoVerificador {
            get {
                return this.digitoVerificadorField;
            }
            set {
                this.digitoVerificadorField = value;
                this.RaisePropertyChanged("DigitoVerificador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ApellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("ApellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ApellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("ApellidoMaterno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas")]
    public partial class Usuario : Persona {
        
        private string userIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas")]
    public partial class Deudor : Persona {
        
        private Direccion[] direccionesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Direccion[] Direcciones {
            get {
                return this.direccionesField;
            }
            set {
                this.direccionesField = value;
                this.RaisePropertyChanged("Direcciones");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Banmedica.cl/Recaudaciones/Bancobro/Planillas")]
    public partial class RepresentanteLegal : Persona {
        
        private string cambioInformacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CambioInformacion {
            get {
                return this.cambioInformacionField;
            }
            set {
                this.cambioInformacionField = value;
                this.RaisePropertyChanged("CambioInformacion");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PlanillasSoapChannel : WS_Ingresos.PlanillasServices.PlanillasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlanillasSoapClient : System.ServiceModel.ClientBase<WS_Ingresos.PlanillasServices.PlanillasSoap>, WS_Ingresos.PlanillasServices.PlanillasSoap {
        
        public PlanillasSoapClient() {
        }
        
        public PlanillasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlanillasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlanillasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlanillasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool PagarPlanillas(long folio, string isapre, string formapago) {
            return base.Channel.PagarPlanillas(folio, isapre, formapago);
        }
        
        public System.Threading.Tasks.Task<bool> PagarPlanillasAsync(long folio, string isapre, string formapago) {
            return base.Channel.PagarPlanillasAsync(folio, isapre, formapago);
        }
        
        public WS_Ingresos.PlanillasServices.Planilla ObtenerPlanillasPorFolioPago(long folio) {
            return base.Channel.ObtenerPlanillasPorFolioPago(folio);
        }
        
        public System.Threading.Tasks.Task<WS_Ingresos.PlanillasServices.Planilla> ObtenerPlanillasPorFolioPagoAsync(long folio) {
            return base.Channel.ObtenerPlanillasPorFolioPagoAsync(folio);
        }
        
        public WS_Ingresos.PlanillasServices.Respuesta ObtenerPlanilla(long folio) {
            return base.Channel.ObtenerPlanilla(folio);
        }
        
        public System.Threading.Tasks.Task<WS_Ingresos.PlanillasServices.Respuesta> ObtenerPlanillaAsync(long folio) {
            return base.Channel.ObtenerPlanillaAsync(folio);
        }
    }
}
